"""Names a bot borrows for as long as it is sitting at a table.

Picked fresh every time one sits down, and never two of the same at the
same moment anywhere on the network -- a table is meant to look like a
room of strangers, and the same handful of names turning up hand after
hand is what gives that away.
"""

from __future__ import annotations


BOT_NAMES: tuple[str, ...] = (
    "Килиманжаро",
    "Клубни4ка",
    "Не гей",
    "Гей",
    "Ты пидор",
    "Жижа",
    "Антон Загубин",
    "xXПельменьXx",
    "Вася_2007",
    "admin_подвала",
    "modem",
    "dialup",
    "kazantip.exe",
    "DarkAngel88",
    "xXDeadSoulXx",
    "SilentKiller",
    "LonelyWolf",
    "DarkPhoenix",
    "BlackRaven",
    "Вася_Пупкин",
    "Кот_В_Сапогах",
    "Кровавый_Мальчик",
    "Тёмный_Рыцарь",
    "Одинокий_Волк",
    "Девочка_С_Проблемами",
    "Пацан_С_Района",
    "Без_Паники",
    "Просто_Я",
    "-=DarkAngel=-",
    "~SweetGirl~",
    "Shadow",
    "xXx_Nikita_xXx",
    "-=Killer=-",
    "[Diablo]",
    "-=NoName=-",
    "~CrazyGirl~",
    "DarkPaladin",
    "ShadowPriest",
    "BloodKnight",
    "NightElf",
    "SoulHunter",
    "DeathWalker",
    "MoonRider",
    "Васян_007",
    "Killer_666",
    "Angel_13",
    "Devil_666",
    "Maximus_2000",
    "Sasha_1991",
    "Crazy_88",
    "xXxBrokenHeartxXx",
    "deadinside",
    "cryingangel",
    "lost_in_darkness",
    "bleeding_soul",
    "nobodyknows",
    "forgottenboy",
    "broken_dreams",
    "KafkaReader",
    "PingPongVonLaserstein",
    "SonikkuJ",
    "LieutenantMalaise",
    "Wingnut",
    "Plorfu",
    "gandalas",
    "shuke",
    "DocLaserstein",
    "suicide_silence",
    "black_roses",
    "tears_of_angel",
    "lonely_forever",
    "fall_to_pieces",
    "empty_inside",
    "dead_romance",
    "Black_666",
    "Dark_777",
    "Wolf_666",
    "NEO_2007",
    "Matrix_88",
    "Terminator_007",
    "Ghost_666",
    "Admin_777",
    "ChaosLord",
    "DarkMage",
    "FrostBlade",
    "DemonHunter",
    "BlackWizard",
    "SoulReaper",
    "HellSpawn",
    "CrimsonWolf",
    "Dark",
    "~*Angel*~",
    "xXxDeadxXx",
    "-=Virus=-",
    "[OFFLINE]",
    "[No_Friends]",
    "JustMe",
    "Не_Трогай",
    "Чувак_2007",
    "Мистер_Х",
    "КотЭ",
    "Злой_Админ",
    "Лорд_Тьмы",
    "CyberAngel",
    "NightHunter",
    "ShadowLord",
    "AngelOfDeath",
    "FrozenHeart",
    "SweetDevil",
    "BrokenAngel",
    "DarkPrincess",
    "LostSoul",
    "WinRar",
    "наследник микроволновки",
    "папка_новая",
    "файл2",
    "князь гаражного кооператива",
    "локальный_диск",
    "неизвестный_номер",
    "пользователь_2",
    "Фунтик",
    "Сторож",
    "Предел",
    "Свидетель",
    "Запасной",
    "Экземпляр",
    "Параграф",
    "Контакт",
    "Резерв",
    "Борис Шумов",
    "Клим Забылов",
    "Яромир Пятницкий",
    "Глеб Остывший",
    "Артур Непонятный",
    "Фома Вчерашний",
    "Игорь Потом",
    "Владислав Случайный",
    "Лев Нормальный",
    "Максим Уже",
    "Гоша Рубчинский",
    "Министерство Внутреннего Ветра",
    "Архив Ненужной Информации",
    "Отдел Поиска Второго Носка",
    "Гоша Ватрушкин",
    "Эдгар Пупкин",
    "Аркадий Шлёпин",
    "квантовый дворник",
    "Институт Неловких Решений",
    "Федеральное Бюро Тапок",
    "Центр Потерянных Мыслей",
    "Комитет По Делам Голубей",
    "Андрей",
    "Вторник",
    "Ничего",
    "Потом",
    "Объект",
    "Пользователь",
    "Результат",
    "Причина",
    "Пункт",
    "дед внутри",
    "шаурма premium",
    "сын кассира",
    "котлета online",
    "бомж deluxe",
    "батя в отпуске",
    "голубь 4к",
    "пельмень pro max",
    "носок ultra",
    "сыр без лицензии",
    "afterstatic",
    "velvet error",
    "deadpixel",
    "lowheaven",
    "softcrash",
    "pale noise",
    "emptyframe",
    "cold archive",
    "wrongmemory",
    "almostreal",
    "17:43",
    "почему",
    "404 км",
    "½ человека",
    "третий слева",
    "8 процентов",
    "минус один",
    "не сегодня",
    "версия 7",
    "0007",
    "сектор тишины",
    "нечётная сторона",
    "после последнего",
    "комната 0",
    "архив 17",
    "второй этаж отсутствует",
    "проект «зачем»",
    "объект №6",
    "ЖМЫХ",
    "ЗАЧЕМ",
    "user_not_found",
    "0xПельмень",
    "null",
    "undefined человек",
    "[removed]",
    "loading…",
    "ctrl+жизнь",
    "error 200",
    "без заголовка",
    "new_user_final2",
)
