"""Concatenate the table's v0xx layers into static/table-layers.js.

The layers used to be fetched one at a time, in a waterfall five requests
deep (component-ui -> eight layers -> v037 -> v038 -> v040 -> v041), which
on a real connection was five round trips before the table looked like
the table. One file, in the same order, run at the same moment (after
DOMContentLoaded, from component-ui.js) is the same code with one request.

Each layer still carries its own "is the next one loaded yet?" check on a
marker <script> tag; the prelude plants every marker first, so those
loaders find their layer already present and stand down. The sources stay
readable, and a test keeps this output in step with them.

Run:  python tools/bundle_table_layers.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATIC = ROOT / "static"
OUTPUT = STATIC / "table-layers.js"

#: In the order the loaders used to run them.
LAYERS = (
    "v016-fixes.js",
    "v018-fixes.js",
    "v019-center-polish.js",
    "v023-brand-balance-fix.js",
    "v026-seat-status-layout.js",
    "v027-compact-seats-controls.js",
    "v028-ready-phase.js",
    "v031-pot-cluster-mobile-fix.js",
    "v032-poker8-v2-mobile-sixmax.js",
    "v037-poker8-v2-reference-table.js",
    "v038-poker8-v2-cinematic-table.js",
    "v040-poker8-v2-dynamic-seats.js",
    "v041-poker8-v2-turn-clarity.js",
)

#: The markers the loaders still inside the layers look for before fetching
#: the next one: v028 fetches v031, v037 fetches v038, v040 and v041. The
#: first batch was fetched by component-ui.js, which now fetches this file.
MARKERS = (
    "data-v031-pot-cluster-mobile-fix",
    "data-v038-poker8-v2-cinematic-table",
    "data-v040-poker8-v2-dynamic-seats",
    "data-v041-poker8-v2-turn-clarity",
)


def build() -> str:
    parts = [
        "/* GENERATED by tools/bundle_table_layers.py -- do not edit; edit the\n"
        "   v0xx layer and rebuild. Order is the order the loaders ran them in. */\n",
        "(() => {\n"
        "  // Every layer is already here: plant the marker each loader checks\n"
        "  // for, so none of them fetches what the next lines run anyway.\n"
        "  for (const marker of " + repr(list(MARKERS)).replace("'", '"') + ") {\n"
        "    const tag = document.createElement(\"script\");\n"
        "    tag.setAttribute(marker, \"1\");\n"
        "    document.body.appendChild(tag);\n"
        "  }\n"
        "})();\n",
    ]
    for name in LAYERS:
        source = (STATIC / name).read_text(encoding="utf-8")
        # The ";" is not decoration: "})()" followed by "(() => {" on the next
        # line is a call, and ASI will not save it.
        body = source.rstrip().rstrip(";")
        parts.append(f"\n/* ==== {name} ==== */\n{body};\n")
    return "".join(parts)


if __name__ == "__main__":
    OUTPUT.write_text(build(), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size} bytes, {len(LAYERS)} layers)")
